[package]
name = "rubato"
version = "0.12.0"
rust-version = "1.61"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "Asynchronous resampling library intended for audio data"
license = "MIT"
repository = "https://github.com/HEnquist/rubato"
keywords = ["interpolation", "resampling"]
categories = ["multimedia::audio"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.14", optional = true }
num-complex = "0.4"
num-integer = "0.1.44"
num-traits = "0.2"
easyfft = { path = "../easyfft/" }

[dev-dependencies] 
env_logger = "0.9.0"
criterion = "0.3.5"
rand = "0.8.4"
num-traits = "0.2.14"
log = "0.4.14"

[[bench]]
name = "resamplers"
harness = false

[lib]
bench = false
path = "src/lib.rs"
